/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AchievementIndexRouteImport } from './routes/achievement/index'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as InterviewlistIndexRouteImport } from './routes/interview/(list)/index'
import { Route as AnnouncementlistIndexRouteImport } from './routes/announcement/(list)/index'
import { Route as InterviewdetailIdRouteImport } from './routes/interview/(detail)/$id'
import { Route as AnnouncementdetailIdRouteImport } from './routes/announcement/(detail)/$id'

const AchievementIndexRoute = AchievementIndexRouteImport.update({
  id: '/achievement/',
  path: '/achievement/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewlistIndexRoute = InterviewlistIndexRouteImport.update({
  id: '/interview/(list)/',
  path: '/interview/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementlistIndexRoute = AnnouncementlistIndexRouteImport.update({
  id: '/announcement/(list)/',
  path: '/announcement/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewdetailIdRoute = InterviewdetailIdRouteImport.update({
  id: '/interview/(detail)/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementdetailIdRoute = AnnouncementdetailIdRouteImport.update({
  id: '/announcement/(detail)/$id',
  path: '/announcement/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/achievement/': typeof AchievementIndexRoute
  '/announcement/$id': typeof AnnouncementdetailIdRoute
  '/interview/$id': typeof InterviewdetailIdRoute
  '/announcement/': typeof AnnouncementlistIndexRoute
  '/interview/': typeof InterviewlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/achievement': typeof AchievementIndexRoute
  '/announcement/$id': typeof AnnouncementdetailIdRoute
  '/interview/$id': typeof InterviewdetailIdRoute
  '/announcement': typeof AnnouncementlistIndexRoute
  '/interview': typeof InterviewlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/achievement/': typeof AchievementIndexRoute
  '/announcement/(detail)/$id': typeof AnnouncementdetailIdRoute
  '/interview/(detail)/$id': typeof InterviewdetailIdRoute
  '/announcement/(list)/': typeof AnnouncementlistIndexRoute
  '/interview/(list)/': typeof InterviewlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievement/'
    | '/announcement/$id'
    | '/interview/$id'
    | '/announcement/'
    | '/interview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievement'
    | '/announcement/$id'
    | '/interview/$id'
    | '/announcement'
    | '/interview'
  id:
    | '__root__'
    | '/(home)/'
    | '/achievement/'
    | '/announcement/(detail)/$id'
    | '/interview/(detail)/$id'
    | '/announcement/(list)/'
    | '/interview/(list)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  AchievementIndexRoute: typeof AchievementIndexRoute
  AnnouncementdetailIdRoute: typeof AnnouncementdetailIdRoute
  InterviewdetailIdRoute: typeof InterviewdetailIdRoute
  AnnouncementlistIndexRoute: typeof AnnouncementlistIndexRoute
  InterviewlistIndexRoute: typeof InterviewlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/achievement/': {
      id: '/achievement/'
      path: '/achievement'
      fullPath: '/achievement/'
      preLoaderRoute: typeof AchievementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/(list)/': {
      id: '/interview/(list)/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof InterviewlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement/(list)/': {
      id: '/announcement/(list)/'
      path: '/announcement'
      fullPath: '/announcement/'
      preLoaderRoute: typeof AnnouncementlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/(detail)/$id': {
      id: '/interview/(detail)/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewdetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement/(detail)/$id': {
      id: '/announcement/(detail)/$id'
      path: '/announcement/$id'
      fullPath: '/announcement/$id'
      preLoaderRoute: typeof AnnouncementdetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  AchievementIndexRoute: AchievementIndexRoute,
  AnnouncementdetailIdRoute: AnnouncementdetailIdRoute,
  InterviewdetailIdRoute: InterviewdetailIdRoute,
  AnnouncementlistIndexRoute: AnnouncementlistIndexRoute,
  InterviewlistIndexRoute: InterviewlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
