/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewsIndexRouteImport } from './routes/interviews.index'
import { Route as AchievementsIndexRouteImport } from './routes/achievements.index'
import { Route as InterviewsIdRouteImport } from './routes/interviews.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIndexRoute = InterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsIndexRoute = AchievementsIndexRouteImport.update({
  id: '/achievements/',
  path: '/achievements/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIdRoute = InterviewsIdRouteImport.update({
  id: '/interviews/$id',
  path: '/interviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/achievements': typeof AchievementsIndexRoute
  '/interviews': typeof InterviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/interviews/$id' | '/achievements/' | '/interviews/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/interviews/$id' | '/achievements' | '/interviews'
  id: '__root__' | '/' | '/interviews/$id' | '/achievements/' | '/interviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InterviewsIdRoute: typeof InterviewsIdRoute
  AchievementsIndexRoute: typeof AchievementsIndexRoute
  InterviewsIndexRoute: typeof InterviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/': {
      id: '/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof InterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements/': {
      id: '/achievements/'
      path: '/achievements'
      fullPath: '/achievements/'
      preLoaderRoute: typeof AchievementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/$id': {
      id: '/interviews/$id'
      path: '/interviews/$id'
      fullPath: '/interviews/$id'
      preLoaderRoute: typeof InterviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InterviewsIdRoute: InterviewsIdRoute,
  AchievementsIndexRoute: AchievementsIndexRoute,
  InterviewsIndexRoute: InterviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
