/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecruitIndexRouteImport } from './routes/recruit/index'
import { Route as MemberIndexRouteImport } from './routes/member/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AchievementIndexRouteImport } from './routes/achievement/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as ReportlistIndexRouteImport } from './routes/report/(list)/index'
import { Route as InterviewlistIndexRouteImport } from './routes/interview/(list)/index'
import { Route as AnnouncementlistIndexRouteImport } from './routes/announcement/(list)/index'
import { Route as ReportdetailIdRouteImport } from './routes/report/(detail)/$id'
import { Route as InterviewdetailIdRouteImport } from './routes/interview/(detail)/$id'
import { Route as AnnouncementdetailIdRouteImport } from './routes/announcement/(detail)/$id'

const RecruitIndexRoute = RecruitIndexRouteImport.update({
  id: '/recruit/',
  path: '/recruit/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/member/',
  path: '/member/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementIndexRoute = AchievementIndexRouteImport.update({
  id: '/achievement/',
  path: '/achievement/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportlistIndexRoute = ReportlistIndexRouteImport.update({
  id: '/report/(list)/',
  path: '/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewlistIndexRoute = InterviewlistIndexRouteImport.update({
  id: '/interview/(list)/',
  path: '/interview/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementlistIndexRoute = AnnouncementlistIndexRouteImport.update({
  id: '/announcement/(list)/',
  path: '/announcement/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportdetailIdRoute = ReportdetailIdRouteImport.update({
  id: '/report/(detail)/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewdetailIdRoute = InterviewdetailIdRouteImport.update({
  id: '/interview/(detail)/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementdetailIdRoute = AnnouncementdetailIdRouteImport.update({
  id: '/announcement/(detail)/$id',
  path: '/announcement/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/about/': typeof AboutIndexRoute
  '/achievement/': typeof AchievementIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/member/': typeof MemberIndexRoute
  '/recruit/': typeof RecruitIndexRoute
  '/announcement/$id': typeof AnnouncementdetailIdRoute
  '/interview/$id': typeof InterviewdetailIdRoute
  '/report/$id': typeof ReportdetailIdRoute
  '/announcement/': typeof AnnouncementlistIndexRoute
  '/interview/': typeof InterviewlistIndexRoute
  '/report/': typeof ReportlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/about': typeof AboutIndexRoute
  '/achievement': typeof AchievementIndexRoute
  '/contact': typeof ContactIndexRoute
  '/member': typeof MemberIndexRoute
  '/recruit': typeof RecruitIndexRoute
  '/announcement/$id': typeof AnnouncementdetailIdRoute
  '/interview/$id': typeof InterviewdetailIdRoute
  '/report/$id': typeof ReportdetailIdRoute
  '/announcement': typeof AnnouncementlistIndexRoute
  '/interview': typeof InterviewlistIndexRoute
  '/report': typeof ReportlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/about/': typeof AboutIndexRoute
  '/achievement/': typeof AchievementIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/member/': typeof MemberIndexRoute
  '/recruit/': typeof RecruitIndexRoute
  '/announcement/(detail)/$id': typeof AnnouncementdetailIdRoute
  '/interview/(detail)/$id': typeof InterviewdetailIdRoute
  '/report/(detail)/$id': typeof ReportdetailIdRoute
  '/announcement/(list)/': typeof AnnouncementlistIndexRoute
  '/interview/(list)/': typeof InterviewlistIndexRoute
  '/report/(list)/': typeof ReportlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/achievement/'
    | '/contact/'
    | '/member/'
    | '/recruit/'
    | '/announcement/$id'
    | '/interview/$id'
    | '/report/$id'
    | '/announcement/'
    | '/interview/'
    | '/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievement'
    | '/contact'
    | '/member'
    | '/recruit'
    | '/announcement/$id'
    | '/interview/$id'
    | '/report/$id'
    | '/announcement'
    | '/interview'
    | '/report'
  id:
    | '__root__'
    | '/(home)/'
    | '/about/'
    | '/achievement/'
    | '/contact/'
    | '/member/'
    | '/recruit/'
    | '/announcement/(detail)/$id'
    | '/interview/(detail)/$id'
    | '/report/(detail)/$id'
    | '/announcement/(list)/'
    | '/interview/(list)/'
    | '/report/(list)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AchievementIndexRoute: typeof AchievementIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  MemberIndexRoute: typeof MemberIndexRoute
  RecruitIndexRoute: typeof RecruitIndexRoute
  AnnouncementdetailIdRoute: typeof AnnouncementdetailIdRoute
  InterviewdetailIdRoute: typeof InterviewdetailIdRoute
  ReportdetailIdRoute: typeof ReportdetailIdRoute
  AnnouncementlistIndexRoute: typeof AnnouncementlistIndexRoute
  InterviewlistIndexRoute: typeof InterviewlistIndexRoute
  ReportlistIndexRoute: typeof ReportlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recruit/': {
      id: '/recruit/'
      path: '/recruit'
      fullPath: '/recruit/'
      preLoaderRoute: typeof RecruitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/member'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievement/': {
      id: '/achievement/'
      path: '/achievement'
      fullPath: '/achievement/'
      preLoaderRoute: typeof AchievementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/(list)/': {
      id: '/report/(list)/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/(list)/': {
      id: '/interview/(list)/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof InterviewlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement/(list)/': {
      id: '/announcement/(list)/'
      path: '/announcement'
      fullPath: '/announcement/'
      preLoaderRoute: typeof AnnouncementlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/(detail)/$id': {
      id: '/report/(detail)/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportdetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/(detail)/$id': {
      id: '/interview/(detail)/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewdetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement/(detail)/$id': {
      id: '/announcement/(detail)/$id'
      path: '/announcement/$id'
      fullPath: '/announcement/$id'
      preLoaderRoute: typeof AnnouncementdetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  AchievementIndexRoute: AchievementIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  MemberIndexRoute: MemberIndexRoute,
  RecruitIndexRoute: RecruitIndexRoute,
  AnnouncementdetailIdRoute: AnnouncementdetailIdRoute,
  InterviewdetailIdRoute: InterviewdetailIdRoute,
  ReportdetailIdRoute: ReportdetailIdRoute,
  AnnouncementlistIndexRoute: AnnouncementlistIndexRoute,
  InterviewlistIndexRoute: InterviewlistIndexRoute,
  ReportlistIndexRoute: ReportlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
